import Image from "next/image";
import { ArrowRight, CheckCircle2, Code2, Mail, MapPin, Phone, Rocket, UsersRound } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { SiteHeader } from "@/components/site-header";
import { homeContent, siteConfig } from "@/data/site";
import { HomePage } from "@/components/home-page";

const serviceIcons = { code: Code2, users: UsersRound, rocket: Rocket };

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="max-w-2xl"><p className="text-sm font-bold tracking-[0.14em] text-brand uppercase">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-ink sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-lg leading-8 text-slate-600">{text}</p>}</div>;
}

export function LegacyHome() {
  const { hero, services, about, process, team, contact } = homeContent;
  return <main><SiteHeader />
    <section className="overflow-hidden bg-[linear-gradient(135deg,#edf8ff_0%,#fff_55%,#e9f4ff_100%)]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div className="self-center"><p className="mb-5 text-sm font-bold tracking-[0.15em] text-brand uppercase">Pune · India</p><h1 className="max-w-3xl text-5xl font-bold tracking-tight text-ink sm:text-6xl">Technology that moves your business forward.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">DA Software Systems creates practical business automation, custom software, and technology solutions that help organisations work smarter and grow with confidence.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#contact" className="inline-flex items-center gap-2 rounded-full bg-brand px-6 py-3.5 font-semibold text-white transition hover:bg-brand-deep">Discuss your project <ArrowRight size={18} /></a><a href="#services" className="rounded-full border border-slate-300 px-6 py-3.5 font-semibold text-ink transition hover:border-brand hover:text-brand">Explore services</a></div></div><div className="relative min-h-80 rounded-3xl bg-ink p-8 shadow-2xl shadow-sky-950/20 sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,#249bd9,transparent_35%),radial-gradient(circle_at_15%_80%,#0b4b78,transparent_40%)]" /><div className="relative flex h-full flex-col justify-end"><p className="text-sm font-semibold tracking-[0.14em] text-sky-200 uppercase">Built around your goals</p><p className="mt-3 text-3xl font-semibold leading-tight text-white">From strategy to launch, we make complex digital work feel clear and achievable.</p></div></div></div></section>
    <section id="services" className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="What we do" title="Solutions shaped for your business." text="We combine business understanding with disciplined engineering to deliver useful, maintainable software." /><div className="mt-12 grid gap-5 md:grid-cols-3">{services.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-200 p-7 transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-lg"><Icon className="text-brand" size={30} /><h3 className="mt-6 text-xl font-bold text-ink">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>
    <section id="about" className="bg-mist"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow="About us" title="A partner for business automation and innovation." text="DA Software Systems is a Pune-based software and business-solutions company. Since 2020, we have helped organisations bridge the gap between business needs and technology." /></div><div className="rounded-2xl bg-white p-8 shadow-sm ring-1 ring-slate-200"><h3 className="text-xl font-bold text-ink">Our commitment</h3><p className="mt-4 leading-7 text-slate-600">We listen carefully, plan thoughtfully, and deliver with quality. Our work spans business automation, healthcare, agro-chemical, transport, and hospital-management solutions.</p><ul className="mt-6 grid gap-3 text-sm font-medium text-slate-700 sm:grid-cols-2">{["Collaborative", "Responsible", "Continuously improving", "Focused on quality"].map(item => <li key={item} className="flex items-center gap-2"><CheckCircle2 size={18} className="text-brand" />{item}</li>)}</ul></div></div></section>
    <section id="process" className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="How we work" title="A clear path from first conversation to launch." text="Every engagement is unique, but a repeatable process keeps decisions transparent and outcomes on track." /><ol className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{process.map((step, index) => <li key={step} className="rounded-xl border border-slate-200 p-5"><span className="text-sm font-bold text-brand">0{index + 1}</span><h3 className="mt-6 font-bold text-ink">{step}</h3></li>)}</ol></section>
    <section id="team" className="bg-ink"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><p className="text-sm font-bold tracking-[0.14em] text-sky-300 uppercase">Our people</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-4xl">Meet the team behind the work.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">Our growing team brings practical experience across delivery, engineering, and client service.</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{team.map(([image, name, role]) => <article key={name} className="overflow-hidden rounded-2xl bg-white"><Image src={image} alt={name} width={500} height={500} className="aspect-square w-full object-cover" /><div className="p-5"><h3 className="font-bold text-ink">{name}</h3><p className="mt-1 text-sm text-slate-600">{role}</p></div></article>)}</div></div></section>
    <section id="contact" className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow="Contact" title="Let’s talk about what you need to build." text="Tell us a little about your project and we’ll help you identify a practical next step." /><div className="mt-9 grid gap-5 text-slate-700"><a href="mailto:dasoftwaresystems@gmail.com" className="flex items-start gap-3 hover:text-brand"><Mail className="mt-1 text-brand" size={20} /><span><strong className="block text-ink">Email</strong>dasoftwaresystems@gmail.com</span></a><a href="tel:+919529418046" className="flex items-start gap-3 hover:text-brand"><Phone className="mt-1 text-brand" size={20} /><span><strong className="block text-ink">Phone</strong>+91 95294 18046</span></a><p className="flex items-start gap-3"><MapPin className="mt-1 shrink-0 text-brand" size={20} /><span><strong className="block text-ink">Office</strong>304, Ganesh Nagar, Wadgaonsheri, Viman Nagar, Pune 411014</span></p></div></div><div className="rounded-2xl bg-mist p-6 sm:p-8"><ContactForm /></div></section>
    <footer className="bg-slate-950"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-8 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>© {new Date().getFullYear()} DA Software Systems. All rights reserved.</p><div className="flex gap-5"><a href="/privacy-policy" className="hover:text-white">Privacy policy</a><a href="/account-deletion" className="hover:text-white">Account deletion</a></div></div></footer>
  </main>;
}

export default function Home() {
  return <HomePage />;
}
