import Image from "next/image";
import { ArrowRight, CheckCircle2, Code2, Mail, MapPin, Phone, Rocket, UsersRound } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { SiteHeader } from "@/components/site-header";
import { homeContent, siteConfig } from "@/data/site";

const serviceIcons = { code: Code2, users: UsersRound, rocket: Rocket };

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="max-w-2xl"><p className="text-sm font-bold tracking-[0.14em] text-brand uppercase">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-ink sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-lg leading-8 text-slate-600">{text}</p>}</div>;
}

export function HomePage() {
  const { hero, services, about, process, team, contact } = homeContent;
  return <main><SiteHeader />
    <section className="overflow-hidden bg-[linear-gradient(135deg,#edf8ff_0%,#fff_55%,#e9f4ff_100%)]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div className="self-center"><p className="mb-5 text-sm font-bold tracking-[0.15em] text-brand uppercase">{hero.eyebrow}</p><h1 className="max-w-3xl text-5xl font-bold tracking-tight text-ink sm:text-6xl">{hero.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{hero.description}</p><div className="mt-9 flex flex-wrap gap-4"><a href={hero.primaryCta.href} className="inline-flex items-center gap-2 rounded-full bg-brand px-6 py-3.5 font-semibold text-white transition hover:bg-brand-deep">{hero.primaryCta.label} <ArrowRight size={18} /></a><a href={hero.secondaryCta.href} className="rounded-full border border-slate-300 px-6 py-3.5 font-semibold text-ink transition hover:border-brand hover:text-brand">{hero.secondaryCta.label}</a></div></div><div className="relative min-h-80 rounded-3xl bg-ink p-8 shadow-2xl shadow-sky-950/20 sm:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,#249bd9,transparent_35%),radial-gradient(circle_at_15%_80%,#0b4b78,transparent_40%)]" /><div className="relative flex h-full flex-col justify-end"><p className="text-sm font-semibold tracking-[0.14em] text-sky-200 uppercase">{hero.panelEyebrow}</p><p className="mt-3 text-3xl font-semibold leading-tight text-white">{hero.panelText}</p></div></div></div></section>
    <section id="services" className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><SectionTitle eyebrow={services.eyebrow} title={services.title} text={services.description} /><div className="mt-12 grid gap-5 md:grid-cols-3">{services.items.map(({ icon, title, text }) => { const Icon = serviceIcons[icon]; return <article key={title} className="rounded-2xl border border-slate-200 p-7 transition hover:-translate-y-1 hover:border-sky-200 hover:shadow-lg"><Icon className="text-brand" size={30} /><h3 className="mt-6 text-xl font-bold text-ink">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>; })}</div></section>
    <section id="about" className="bg-mist"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow={about.eyebrow} title={about.title} text={about.description} /></div><div className="rounded-2xl bg-white p-8 shadow-sm ring-1 ring-slate-200"><h3 className="text-xl font-bold text-ink">{about.commitmentTitle}</h3><p className="mt-4 leading-7 text-slate-600">{about.commitmentText}</p><ul className="mt-6 grid gap-3 text-sm font-medium text-slate-700 sm:grid-cols-2">{about.values.map(item => <li key={item} className="flex items-center gap-2"><CheckCircle2 size={18} className="text-brand" />{item}</li>)}</ul></div></div></section>
    <section id="process" className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><SectionTitle eyebrow={process.eyebrow} title={process.title} text={process.description} /><ol className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{process.items.map((step, index) => <li key={step} className="rounded-xl border border-slate-200 p-5"><span className="text-sm font-bold text-brand">0{index + 1}</span><h3 className="mt-6 font-bold text-ink">{step}</h3></li>)}</ol></section>
    <section id="team" className="bg-ink"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><p className="text-sm font-bold tracking-[0.14em] text-sky-300 uppercase">{team.eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-4xl">{team.title}</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{team.description}</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{team.members.map(({ image, name, role }) => <article key={name} className="overflow-hidden rounded-2xl bg-white"><Image src={image} alt={name} width={500} height={500} className="aspect-square w-full object-cover" /><div className="p-5"><h3 className="font-bold text-ink">{name}</h3><p className="mt-1 text-sm text-slate-600">{role}</p></div></article>)}</div></div></section>
    <section id="contact" className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow={contact.eyebrow} title={contact.title} text={contact.description} /><div className="mt-9 grid gap-5 text-slate-700"><a href={`mailto:${siteConfig.contact.email}`} className="flex items-start gap-3 hover:text-brand"><Mail className="mt-1 text-brand" size={20} /><span><strong className="block text-ink">Email</strong>{siteConfig.contact.email}</span></a><a href={siteConfig.contact.phoneHref} className="flex items-start gap-3 hover:text-brand"><Phone className="mt-1 text-brand" size={20} /><span><strong className="block text-ink">Phone</strong>{siteConfig.contact.phone}</span></a><p className="flex items-start gap-3"><MapPin className="mt-1 shrink-0 text-brand" size={20} /><span><strong className="block text-ink">Office</strong>{siteConfig.contact.address}</span></p></div></div><div className="rounded-2xl bg-mist p-6 sm:p-8"><ContactForm /></div></section>
    <footer className="bg-slate-950"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-8 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>Copyright {new Date().getFullYear()} {siteConfig.name}. All rights reserved.</p><div className="flex gap-5">{siteConfig.footerLinks.map(link => <a key={link.href} href={link.href} className="hover:text-white">{link.label}</a>)}</div></div></footer>
  </main>;
}
